#!/bin/bash
resolveip() {
    host=$2
    if [[ $host =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        echo "$host"
    else
        ip=$(getent ahostsv4 "$host" | head -1 | awk '{print $1}')
    fi
}
export -f resolveip
bash /usr/local/bin/ss-rule -c /etc/shadowsocks-libev/redir.json -i /etc/chnroute.list -e "-m multiport --dports 22,53,80,8000,443,587,993,5222,5228" -o "$@"
