---
- name: systemctl daemon-reload
  command: systemctl daemon-reload

- name: restart hass
  service:
    name: hass
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart zigbee2mqtt
  service:
    name: zigbee2mqtt
    state: restarted
