---
- name: install systemd service for shadowsocks local
  copy:
    src: shadowsocks-local.service
    dest: /etc/systemd/system/

- name: config for shadowsocks local
  copy:
    dest: /etc/shadowsocks-libev/local.json
    content: "{{ shadowsocks | to_nice_json }}"
    owner: proxy
    group: staff
    mode: 0640
  notify: restart shadowsocks-local

- name: enable systemd service for shadowsocks local
  service:
    name: shadowsocks-local
    state: started
    enabled: yes

- name: install tinyproxy
  apt:
    name: tinyproxy

- name: config tinyproxy
  template:
    dest: /etc/tinyproxy/tinyproxy.conf
    src: tinyproxy.conf.j2
  notify: restart tinyproxy
