---
- name: install kcptun client
  get_url:
    dest: /usr/local/bin/kcptun-client
    url: https://github.com/azuwis/blob/raw/master/kcptun-client
    sha256sum: 56b265f81b8929446a43ff7c514a531dee10b0d97f02da93eddb8f224b184144
    mode: '0755'

- name: create kcptun config directory
  file:
    dest: /etc/kcptun-client/
    state: directory

- name: create kcptun log directory
  file:
    dest: /var/log/kcptun-client/
    state: directory
    owner: proxy
    group: staff
    mode: '0750'

- name: kcptun client config
  copy:
    dest: /etc/kcptun-client/{{ item.name }}.json
    content: "{{ item.config | to_nice_json }}"
    mode: '0640'
    owner: proxy
    group: staff
  with_items: "{{ kcptun_client }}"
  notify: restart kcptun-client

- name: install kcptun client service
  copy:
    dest: /etc/systemd/system/kcptun-client@.service
    src: kcptun-client@.service
  notify:
    - systemctl daemon-reload
    - restart kcptun-client

- name: enable kcptun client service
  service:
    name: kcptun-client@{{ item.name }}
    enabled: yes
    state: started
  with_items: "{{ kcptun_client }}"

- name: kcptun logrotate config
  copy:
    dest: /etc/logrotate.d/kcptun-client
    src: kcptun-client.logrotate
