---
keyboard:
    xkboptions: ctrl:swapcaps,terminate:ctrl_alt_bksp

font:
  pkgs:
    - fonts-fira
    - fonts-roboto
    - fonts-croscore
    - fonts-crosextra-caladea
    - fonts-crosextra-carlito
    - fonts-noto-cjk
    - fonts-font-awesome
  sans:
    - Fira Sans
    - Noto Sans CJK SC
  serif:
    - Tinos
    - Noto Serif CJK SC
  monospace:
    - Fira Mono
    - Noto Sans Mono CJK SC
  substitutions:
    - origin: Arial
      substitution: Fira Sans

theme:
  pkgs:
    - gtk2-engines-pixbuf
    - arc-theme
    - paper-icon-theme
    - paper-cursor-theme
    - qt5-style-plugins
  # git:
  #   - dest: /usr/share/themes/Flat-Plat-Blue/
  #     repo: https://github.com/peterychuang/Flat-Plat-Blue.git
  icon: Paper
  gtk2: Arc-Darker
  gtk3: Arc-Darker
  qt4: GTK+
  qt5: gtk2

browser:
  default: firefox
