---
- hosts: nuc
  vars:
    domain: localdomain
    staff:
      - name: azuwis
        comment: Zhong Jianxin
        uid: 1000
        shell: /bin/zsh
  roles:
    - staff
    - apt
    - base
    - systemd
    - desktop_base
    - wireless
    - xbmc
    - torrent
