---
- hosts: nuc
  become: yes
  vars:
    dpi: 160
    eth: eno1
    extra_packages:
      - firmware-misc-nonfree
    kernel_modules:
      - i915
  roles:
    - { role: apt, tags: apt }
    - { role: base, tags: base }
    - { role: staff, tags: staff }
    - { role: desktop_base, tags: desktop_base }
    - { role: dictionary, tags: dictionary }
    - { role: music, tags: music }
    - { role: wireless, tags: wireless }
    - { role: tcp-bbr, tags: tcp-bbr }

    - { role: kodi, tags: kodi }
    - { role: torrent, tags: torrent }
    - { role: sysrqd, tags: sysrqd }
    - { role: mactelnet-server, tags: mactelnet-server }
    - { role: adb, tags: adb }
    - { role: mlvpn, tags: mlvpn }
    - { role: bluetooth_audio, tags: bluetooth_audio }
    # - { role: kcptun-client, tags: kcptun-client }
    # - { role: arukas, tags: arukas }
    # - { role: certbot, tags: certbot }
