---
- hosts: nuc
  vars:
    domain: localdomain
    staff:
      - name: azuwis
        comment: Zhong Jianxin
        uid: 1000
        shell: /bin/zsh
  roles:
    - { role: staff, tags: staff }
    - { role: apt, tags: apt }
    - { role: base, tags: base }
    - { role: desktop_base, tags: desktop_base }
    - { role: wireless, tags: wireless }
    - { role: bluetooth, tags: bluetooth }
    - { role: xbmc, tags: xbmc }
    - { role: torrent, tags: torrent }
