---
- hosts: nuc
  roles:
    - role: staff
      name: azuwis
      comment: "Zhong Jianxin"
      uid: 1000
    - apt
    - base
    - systemd
    - desktop_base
    - wireless
    - xbmc
    - torrent
