---
- hosts: nuc
  become: yes
  vars:
    dpi: 160
    extra_packages:
      - firmware-misc-nonfree
      - vlan
    # kernel_modules:
    #   - i915
    #   - 8021q
  roles:
    - { role: apt, tags: apt }
    - { role: base, tags: base }
    - { role: staff, tags: staff }
    - { role: desktop_base, tags: desktop_base }
    - { role: dictionary, tags: dictionary }
    - { role: wireless, tags: wireless }
    - { role: tcp-bbr, tags: tcp-bbr }

    # - { role: kodi, tags: kodi }
    - { role: torrent, tags: torrent }
    - { role: torrent-ratio, tags: torrent-ratio }
    - { role: samba, tags: samba }
    # - { role: sysrqd, tags: sysrqd }
    # - { role: mactelnet-server, tags: mactelnet-server }
    - { role: adb, tags: adb }
    - { role: bluetooth_audio, tags: bluetooth_audio }
    # - { role: dehydrated, tags: dehydrated }
    - { role: motion, tags: motion }
    - { role: hass, tags: hass }

    # - { role: arukas, tags: arukas }
    # - { role: certbot, tags: certbot }
    # - { role: kcptun-client, tags: kcptun-client }
    # - { role: mlvpn, tags: mlvpn }
    # - { role: music, tags: music }
