---
- hosts: nuc
  become: yes
  vars:
    dpi: 160
    eth: eno1
    extra_packages:
      - firmware-misc-nonfree
    kernel_modules:
      - i915
    alsa:
      card: 0
      device: 3
  roles:
    - { role: apt, tags: apt }
    - { role: base, tags: base }
    - { role: staff, tags: staff }
    - { role: desktop_base, tags: desktop_base }
    - { role: dictionary, tags: dictionary }
    - { role: music, tags: music }
    - { role: wireless, tags: wireless }

    - { role: kodi, tags: kodi }
    - { role: torrent, tags: torrent }
    - { role: sysrqd, tags: sysrqd }
    - { role: mactelnet-server, tags: mactelnet-server }
    - { role: certbot, tags: certbot }
