---
- hosts: nuc
  roles:
    - apt
    - pkg_base
    - pkg_systemd
    - pkg_desktop_base
    - pkg_wireless
    - pkg_xbmc
    - role: staff
      name: azuwis
      comment: "Zhong Jianxin"
      uid: 1000
  tasks:
    - name: set hostname
      hostname: name=nuc
    - name: set domain
      lineinfile:
        dest: /etc/hosts
        insertafter: ^127\.0\.0\.1\slocalhost
        line: "127.0.0.1\tnuc.localdomain nuc"
