---
# NOTE:
# * Use debian-installer from http://cdimage.debian.org/cdimage/daily-builds/sid_d-i/arch-latest/amd64/iso-cd/
# * BIOS: 1) Set SATA-controller is set to AHCI, 2) Disable Secure-boot
# * More at https://wiki.archlinux.org/index.php/Dell_XPS_13_(2016)
- hosts: xps
  become: yes
  vars:
    dpi: 168
    extra_packages:
      - firmware-brcm80211
      - firmware-misc-nonfree
      - nvme-cli
    kernel_modules:
      - nvme
      - i915
    blobs:
      - name: BCM-0a5c-6412.hcd
        dest: /lib/firmware/brcm/BCM-0a5c-6412.hcd
        sha256sum: 6e262584f8cd54b08914dd8e978fbf6191fe243a553ecf0dc6653a7b9eeab0b9
  roles:
    - { role: apt, tags: apt }
    - { role: base, tags: base }
    - { role: staff, tags: staff }
    - { role: desktop_base, tags: desktop_base }
    - { role: wireless, tags: wireless }
    - { role: bluetooth, tags: bluetooth }
    - { role: tlp, tags: tlp }
    - { role: dictionary, tags: dictionary }
    - { role: office, tags: office }
    - { role: music, tags: music }

    - { role: adb, tags: adb }
    - { role: email-client, tags: email-client }
