---
# NOTE:
# * BIOS: 1) Set SATA-controller is set to AHCI, 2) Disable Secure-boot
# * Use debian-installer from http://cdimage.debian.org/cdimage/daily-builds/sid_d-i/arch-latest/amd64/iso-cd/
- hosts: xps
  become: yes
  vars:
    domain: localdomain
    dpi: 165
    extra_packages:
      - firmware-brcm80211
      - firmware-misc-nonfree
    kernel_modules:
      - nvme
      - i915
    keyboard:
      xkboptions: ctrl:swapcaps,altwin:swap_lalt_lwin,terminate:ctrl_alt_bksp
    # grub:
    #   cmd: acpi_apic_instance=2
  roles:
    - { role: apt, tags: apt }
    - { role: base, tags: base }
    - { role: staff, tags: staff }
    - { role: desktop_base, tags: desktop_base }
    - { role: wireless, tags: wireless }
    - { role: tlp, tags: tlp }
    - { role: dictionary, tags: dictionary }
    - { role: office, tags: office }

    # - { role: adb, tags: adb }
    # - { role: extra-packages, tags: extra-packages }
    - { role: email-client, tags: email-client }
