---
- name: apt config
  copy: src=99misc dest=/etc/apt/apt.conf.d/99misc

- name: install lsb-release
  apt: name=lsb-release install_recommends=no

- name: reget ansible_lsb.codename if it is empty
  setup:
  when: ansible_lsb is not defined

- name: apt preferences
  template:
    src: preferences.j2
    dest: /etc/apt/preferences

- name: generate /etc/apt/sources.list
  template:
    dest: /etc/apt/sources.list
    src: sources.list.j2
  register: result

- name: update apt package index if needed
  apt:
    update_cache: yes
  when: result.changed

- name: install custom apt key
  copy:
    src: azuwis.gpg
    dest: /etc/apt/trusted.gpg.d/azuwis.gpg
