---
- name: Apt config
  copy: src=99misc dest=/etc/apt/apt.conf.d/99misc

- name: Install lsb-release
  apt: name=lsb-release install_recommends=no

- name: Get ansible_lsb.codename if it's empty
  setup:
  when: ansible_lsb is not defined

# TODO Use template
- name: Remove /etc/apt/sources.list
  file: path=/etc/apt/sources.list state=absent

- name: Main sources.list
  apt_repository: repo='deb http://{{ apt_mirror | default("ftp.cn.debian.org") }}/debian {{ ansible_lsb.codename }} main contrib non-free' state=present

# TODO Split to another role, handle deb-multimedia-keyring
- name: Deb multimedia sources.list
  apt_repository: repo='deb http://www.deb-multimedia.org {{ ansible_lsb.codename }} main non-free' state=present
