---
- name: apt config
  copy: src=99misc dest=/etc/apt/apt.conf.d/99misc

- name: apt preferences
  template:
    src: preferences.j2
    dest: /etc/apt/preferences

- name: install lsb-release
  apt: name=lsb-release install_recommends=no

- name: reget ansible_lsb.codename if it is empty
  setup:
  when: ansible_lsb is not defined

# TODO Use template
- name: remove /etc/apt/sources.list
  file: path=/etc/apt/sources.list state=absent

- name: main sources.list
  apt_repository: repo='deb http://{{ apt_mirror | default("ftp.cn.debian.org") }}/debian {{ ansible_lsb.codename }} main contrib non-free'

- name: experimental sources.list
  apt_repository:
    repo: deb http://{{ apt_mirror | default("ftp.cn.debian.org") }}/debian experimental main
