- name: install jq
  apt:
    name: jq

- name: config netrc
  template:
    dest: ~/.netrc
    src: netrc.j2
    mode: '0600'

- name: copy update-arukas script
  copy:
    dest: /usr/local/bin/update-arukas
    src: update-arukas
    mode: '0755'

- name: cron to update-arukas
  cron:
    name: update arukas
    minute: '*/30'
    job: /usr/local/bin/update-arukas
