---
- name: add apt dpkg hook for bluez
  copy:
    dest: /etc/apt/apt.conf.d/99bluez
    src: 99bluez

- name: install bluez
  apt:
    name: bluez
  notify: setcap l2ping

- name: install bluez-tools
  apt:
    name: bluez-tools

- name: add staffs to bluetooth group
  user:
    name: "{{ item.name }}"
    groups: bluetooth
    append: yes
  with_items: "{{ staff }}"
