---
- name: install bluez
  apt:
    name: bluez
  notify: setcap l2ping

- name: install bluez-tools
  apt:
    name: bluez-tools

- name: add staffs to bluetooth group
  user:
    name: "{{ item.name }}"
    groups: bluetooth
    append: yes
  with_items: "{{ staff }}"
