---
- name: dpkg-reconfigure linux-image
  shell: dpkg-reconfigure -fnoninteractive "linux-image-$(uname -r)"

- name: update timezone
  shell: dpkg-reconfigure --frontend noninteractive tzdata

- name: update grub
  command: update-grub

- name: reload ssh
  service:
    name: ssh
    state: reloaded

- name: restart journald
  service: name=systemd-journald state=restarted
