---
- name: install systemd service for shadowsocks redir
  copy:
    src: shadowsocks-redir.service
    dest: /etc/systemd/system/

- name: config for shadowsocks redir
  template:
    src: redir.json.j2
    dest: /etc/shadowsocks-libev/redir.json
    owner: proxy
    group: staff
    mode: 0640
  notify: restart shadowsocks-redir

- name: install ipset
  apt: name=ipset

- name: install ss-rule
  copy:
    src: shadowsocks.rule
    dest: /usr/local/bin/ss-rule
    owner: root
    group: root
    mode: 0755

- name: install ss-chn
  copy:
    src: ss-chn
    dest: /usr/local/bin/ss-chn
    owner: root
    group: root
    mode: 0755

- name: enable systemd service for shadowsocks redir
  service:
    name: shadowsocks-redir
    state: started
    enabled: yes
