---
- name: install systemd service for shadowsocks redir
  template:
    src: shadowsocks-redir.service.j2
    dest: /etc/systemd/system/shadowsocks-redir.service
  notify: systemctl daemon-reload

- name: config for shadowsocks redir
  copy:
    dest: /etc/shadowsocks-libev/redir.json
    content: "{{ shadowsocks | to_nice_json }}"
    owner: proxy
    group: staff
    mode: 0640
  notify: restart shadowsocks-redir

- name: install nftables
  apt:
    name: nftables

- name: disable nftables service
  service:
    name: nftables
    enabled: no

- name: config for nftables
  template:
    src: nftables.conf.j2
    dest: /etc/shadowsocks-libev/nftables.conf
  notify: restart shadowsocks-redir

- name: enable systemd service for shadowsocks redir
  service:
    name: shadowsocks-redir
    state: started
    enabled: yes
