---
- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: restart chinadns
  service:
    name: chinadns
    state: restarted

- name: restart unbound
  service:
    name: unbound
    state: restarted
