---
- name: install smbios-utils
  apt:
    name: smbios-utils

- name: set keyboard illumination timeout on battery
  command: smbios-keyboard-ctl --set-timeout-battery 30s

- name: set keyboard illumination timeout on ac
  command: smbios-keyboard-ctl --set-timeout-ac 30s

# https://wiki.archlinux.org/index.php/Dell_XPS_13_(2016)#Hissing.2FCrackling_noises_when_using_headphones
- name: headphones crackling noise workaround
  replace:
    dest: /usr/share/pulseaudio/alsa-mixer/paths/analog-input-internal-mic.conf
    regexp: (^\[Element Headphone Mic Boost\]\nswitch = off\nvolume = ).*$
    replace: \1 22

- name: install brcmfmac-suspend service
  copy:
    dest: /etc/systemd/system/brcmfmac-suspend.service
    src: brcmfmac-suspend.service

- name: enable brcmfmac-suspend service
  service:
    name: brcmfmac-suspend
    enabled: yes

- name: install brcmfmac-resume service
  copy:
    dest: /etc/systemd/system/brcmfmac-resume.service
    src: brcmfmac-resume.service

- name: enable brcmfmac-resume service
  service:
    name: brcmfmac-resume
    enabled: yes
