---
- name: install smbios-utils
  apt:
    name: smbios-utils

- name: set keyboard illumination timeout
  command: smbios-keyboard-ctl --set-timeout 30s

# https://wiki.archlinux.org/index.php/Dell_XPS_13_(2016)#Hissing.2FCrackling_noises_when_using_headphones
- name: headphones crackling noise workaround
  command: amixer -c 0 cset 'numid=10' 1
