- id: button_single
  alias: Button single
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/button_bedroom
  condition:
    condition: template
    value_template: "{{ trigger.payload_json.click == 'single' }}"
  action:
    service: light.toggle
    entity_id: light.living_room

- id: button_double
  alias: Button double
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/button_bedroom
  condition:
    condition: template
    value_template: "{{ trigger.payload_json.click == 'double' }}"
  action:
    service: media_player.toggle
    entity_id: media_player.tv

- id: button_long
  alias: Button long
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/button_bedroom
  condition:
    condition: template
    value_template: "{{ trigger.payload_json.click == 'long' }}"
  action:
    service: switch.toggle
    data:
      entity_id: switch.reading_living_room

- id: water_heater
  alias: Water heater
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.water_heater

- id: water_heater_season
  alias: Water heater season
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    condition: template
    value_template: "{{ now().month >= 9 or now().month <= 5 }}"
  action:
    service: switch.turn_on
    data:
      entity_id: switch.water_heater

- id: notify_home
  alias: Notify home
  trigger:
    platform: state
    entity_id:
      - device_tracker.2
    from: 'not_home'
    to: 'home'
  condition:
    condition: time
    after: '8:00'
    before: '21:00'
  action:
    service: notify.html5
    data_template:
      message: >
        {{ state_attr(trigger.entity_id, 'friendly_name') }} arrived home
