- id: water_heater
  alias: Water heater
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  action:
    service: script.water_heater_on

- id: notify_home
  alias: Notify home
  trigger:
    platform: state
    entity_id:
      - device_tracker.2
    from: 'not_home'
    to: 'home'
  condition:
    condition: time
    after: '8:00'
    before: '21:00'
  action:
    service: notify.html5
    data_template:
      message: >
        {{ state_attr(trigger.entity_id, 'friendly_name') }} arrived home
