homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  time_zone: Asia/Shanghai
  unit_system: metric
  customize: !include customize.yaml

frontend:

config:

http:
  server_host: 127.0.0.1

updater:
  reporting: False

# discovery:

conversation:

history:

logbook:

map:

sun:

# sensor:
#   - platform: yr
#     monitored_conditions:
#       - temperature
#       - symbol
#       - humidity

tts:
  - platform: google

binary_sensor:
  - platform: mqtt
    name: motion_living_room
    state_topic: motion/living_room
    device_class: motion

camera:
  - platform: mjpeg
    mjpeg_url: http://127.0.0.1:8081
    name: Living room

climate:
  - platform: xiaomi_miio
    name: AC partner
    host: !secret acpartner_host
    token: !secret acpartner_token
    target_sensor: sensor.ht_bedroom_temperature
    scan_interval: 60

device_tracker:
  - platform: ubus
    host: !secret ubus_host
    username: !secret ubus_username
    password: !secret ubus_password
    dhcp_software: none
    consider_home: 20
    new_device_defaults:
      track_new_devices: False

light:
  - platform: yeelight
    devices:
      !secret yeelight_host:
        name: Living room
        transition: 1000

media_player:
  - platform: braviatv
    host: !secret braviatv_host
    name: TV

mqtt:
  discovery: true
  broker: 127.0.0.1
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

recorder:
  db_url: postgres://@/hass

switch:
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac

  - platform: flux
    lights:
      - light.living_room
    start_time: '7:00'
    stop_time: '23:00'
    start_colortemp: 5000
    sunset_colortemp: 3400
    stop_colortemp: 2700
    mode: mired

  - platform: template
    switches:
      reading:
        friendly_name: Reading
        value_template: "{{ is_state('switch.flux', 'off') }}"
        icon_template: mdi:book-open-page-variant
        turn_on:
          - service: switch.turn_off
            data:
              entity_id: switch.flux
          - service: light.turn_on
            entity_id: light.living_room
            data:
              brightness: 175
              kelvin: 5000
              transition: 30
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.flux

      tv:
        friendly_name: TV
        value_template: "{{ states('media_player.tv') }}"
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.tv
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.tv
        icon_template: >-
          {% if is_state('media_player.tv', 'on') %}
            mdi:television-guide
          {% else %}
            mdi:television
          {% endif %}

      water_heater:
        friendly_name: Water heater
        value_template: "{{ state_attr('climate.ac_partner', 'load_power') | int > 100 }}"
        icon_template: mdi:water
        turn_on:
          - alias: Power button
            service: !secret broadlink_send_packet
            data:
              packet: 'JgBkAAABJ5USExI3ERQROBE4EhMRFBITETgRFBETEhMRFBE4ERQROBITEhMROBE4EjgSEhI4EjcRORE4ERQROBEUERMSExEUETgRFBE4EhMROBI4ETgSNxITETgSAARoAAEnlRIADQUAAAAA'
          - delay: '00:00:01'
          - alias: Heating button
            service: !secret broadlink_send_packet
            data:
              packet: 'JgBkAAABJ5YRExI4ERQROBE4ERQRFBETEjgRExEUEhMSExE4EhMROBEUERMRORI3EjcTEhE4EjgROBE5ETgRFBE4EhMTERITEjcSExEUETgRFRA4EzcROBITETgSAARoAAEolBIADQUAAAAA'
          - wait_template: "{{ state_attr('climate.ac_partner', 'load_power') | int > 100 }}"
            timeout: '00:01:03'
          - condition: template
            value_template: "{{ state_attr('climate.ac_partner', 'load_power') | int < 100 }}"
          - alias: Power button
            service: !secret broadlink_send_packet
            data:
              packet: 'JgBkAAABJ5USExI3ERQROBE4EhMRFBITETgRFBETEhMRFBE4ERQROBITEhMROBE4EjgSEhI4EjcRORE4ERQROBEUERMSExEUETgRFBE4EhMROBI4ETgSNxITETgSAARoAAEnlRIADQUAAAAA'
          - delay: '00:00:01'
          - alias: Heating button
            service: !secret broadlink_send_packet
            data:
              packet: 'JgBkAAABJ5YRExI4ERQROBE4ERQRFBETEjgRExEUEhMSExE4EhMROBEUERMRORI3EjcTEhE4EjgROBE5ETgRFBE4EhMTERITEjcSExEUETgRFRA4EzcROBITETgSAARoAAEolBIADQUAAAAA'
          - wait_template: "{{ state_attr('climate.ac_partner', 'load_power') | int > 100 }}"
            timeout: '00:01:03'
          - condition: template
            value_template: "{{ state_attr('climate.ac_partner', 'load_power') | int < 100 }}"
          - alias: Power button
            service: !secret broadlink_send_packet
            data:
              packet: 'JgBkAAABJ5USExI3ERQROBE4EhMRFBITETgRFBETEhMRFBE4ERQROBITEhMROBE4EjgSEhI4EjcRORE4ERQROBEUERMSExEUETgRFBE4EhMROBI4ETgSNxITETgSAARoAAEnlRIADQUAAAAA'
          - delay: '00:00:01'
          - alias: Heating button
            service: !secret broadlink_send_packet
            data:
              packet: 'JgBkAAABJ5YRExI4ERQROBE4ERQRFBETEjgRExEUEhMSExE4EhMROBEUERMRORI3EjcTEhE4EjgROBE5ETgRFBE4EhMTERITEjcSExEUETgRFRA4EzcROBITETgSAARoAAEolBIADQUAAAAA'
        turn_off:
          - alias: Power button
            service: !secret broadlink_send_packet
            data:
              packet: 'JgBkAAABJ5USExI3ERQROBE4EhMRFBITETgRFBETEhMRFBE4ERQROBITEhMROBE4EjgSEhI4EjcRORE4ERQROBEUERMSExEUETgRFBE4EhMROBI4ETgSNxITETgSAARoAAEnlRIADQUAAAAA'

weather:
  - platform: yweather
    name: Hangzhou
    woeid: 2132574

xiaomi_aqara:
  interface: !secret interface
  gateways:
    - mac: !secret acpartner_mac
      key: !secret acpartner_key

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml

logger:
  default: warning
  logs:
    braviarc.braviarc: critical
    urllib3.connectionpool: critical
    # homeassistant.components.binary_sensor.xiaomi_aqara: debug
    # homeassistant.components.xiaomi_aqara: debug
    # xiaomi_gateway: debug
    # homeassistant.components.climate.xiaomi_miio: debug
