homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  time_zone: Asia/Shanghai
  unit_system: metric
  customize: !include customize.yaml

frontend:

config:

http:
  server_host: 127.0.0.1

updater:
  reporting: no

# discovery:

conversation:

history:

logbook:

map:

sun:

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home

  # - platform: yr
  #   monitored_conditions:
  #     - humidity
  #     - symbol
  #     - temperature

tts:
  - platform: google

binary_sensor:
  - platform: mqtt
    name: motion_living_room
    state_topic: motion/living_room
    device_class: motion

camera:
  - platform: mjpeg
    mjpeg_url: http://127.0.0.1:8081
    name: Living room

climate:
  - platform: xiaomi_miio
    name: AC partner
    host: !secret ac_partner_host
    token: !secret ac_partner_token
    target_sensor: sensor.ht_bedroom_temperature
    scan_interval: 60

  - platform: broadlink
    name: Bedroom
    host: !secret broadlink_host
    mac: !secret broadlink_mac
    ircodes_ini: broadlink_climate_codes/gree.ini
    target_temp: 26
    temp_sensor: sensor.ht_bedroom_temperature

device_tracker:
  - platform: ubus
    host: !secret ubus_host
    username: !secret ubus_username
    password: !secret ubus_password
    dhcp_software: none
    consider_home: 20
    new_device_defaults:
      track_new_devices: no

light:
  - platform: yeelight
    devices:
      !secret yeelight_host:
        name: Living room
        save_on_change: no
        transition: 1000

media_player:
  - platform: braviatv
    host: !secret braviatv_host
    name: TV

mqtt:
  discovery: yes
  broker: 127.0.0.1
  birth_message:
    topic: hass/status
    payload: online
  will_message:
    topic: hass/status
    payload: offline

notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

recorder:
  db_url: postgres://@/hass
  exclude:
    entities:
      - climate.ac_partner
      - switch.tv

switch:
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac

  - platform: flux
    name: flux_living_room
    lights:
      - light.living_room
    start_time: '7:00'
    stop_time: '23:00'
    start_colortemp: 5000
    sunset_colortemp: 3400
    stop_colortemp: 2700
    mode: mired

  - platform: template
    switches:
      reading_living_room:
        friendly_name: Reading living room
        value_template: >-
          {{ is_state('light.living_room', 'on') and is_state('switch.flux_living_room', 'off') }}
        icon_template: mdi:book-open-page-variant
        turn_on:
          - service: switch.turn_off
            data:
              entity_id: switch.flux_living_room
          - service: light.turn_on
            entity_id: light.living_room
            data:
              brightness: 175
              kelvin: 5000
              transition: 30
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.flux_living_room

      tv:
        friendly_name: TV
        value_template: >-
          {{ states('media_player.tv') }}
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.tv
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.tv
        icon_template: mdi:television

      water_heater:
        friendly_name: Water heater
        value_template: >-
          {{ state_attr('climate.ac_partner', 'load_power') | int > 100 }}
        icon_template: mdi:water
        turn_on:
          - alias: Power button
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000005002C2251003600A801C403841388320001000101000000010000000001000100000101010001010101000100000000010001000101010100010410
          - delay: '00:00:01'
          - alias: Heating button
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000006002E2254003600A801C403840D6C138832000100010100000001000000000100010000010101000101010101000100000001000001000101010001043205C0
          - wait_template: >-
              {{ state_attr('climate.ac_partner', 'load_power') | int > 100 }}
            timeout: '00:01:03'
          - condition: template
            value_template: >-
              {{ state_attr('climate.ac_partner', 'load_power') | int < 100 }}
          - alias: Power button
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000005002C2251003600A801C403841388320001000101000000010000000001000100000101010001010101000100000000010001000101010100010410
          - delay: '00:00:01'
          - alias: Heating button
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000006002E2254003600A801C403840D6C138832000100010100000001000000000100010000010101000101010101000100000001000001000101010001043205C0
          - wait_template: >-
              {{ state_attr('climate.ac_partner', 'load_power') | int > 100 }}
            timeout: '00:01:03'
          - condition: template
            value_template: >-
              {{ state_attr('climate.ac_partner', 'load_power') | int < 100 }}
          - alias: Power button
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000005002C2251003600A801C403841388320001000101000000010000000001000100000101010001010101000100000000010001000101010100010410
          - delay: '00:00:01'
          - alias: Heating button
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000006002E2254003600A801C403840D6C138832000100010100000001000000000100010000010101000101010101000100000001000001000101010001043205C0
        turn_off:
          - alias: Power button
            service: climate.xiaomi_miio_send_command
            data:
              command: FE00000000000000000000000005002C2251003600A801C403841388320001000101000000010000000001000100000101010001010101000100000000010001000101010100010410

weather:
  - platform: yweather
    name: Hangzhou
    woeid: 2132574

xiaomi_aqara:
  interface: !secret interface
  gateways:
    - mac: !secret ac_partner_mac
      key: !secret ac_partner_key

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml

logger:
  default: warning
  logs:
    braviarc.braviarc: critical
    urllib3.connectionpool: critical
    # homeassistant.components.binary_sensor.xiaomi_aqara: debug
    # homeassistant.components.xiaomi_aqara: debug
    # xiaomi_gateway: debug
    # homeassistant.components.climate.xiaomi_miio: debug
