homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  time_zone: Asia/Shanghai
  unit_system: metric
  customize: !include customize.yaml

frontend:

config:

http:
  server_host: 127.0.0.1

updater:
  reporting: False

# discovery:

conversation:

history:

logbook:

map:

sun:

# sensor:
#   - platform: yr
#     monitored_conditions:
#       - temperature
#       - symbol
#       - humidity

tts:
  - platform: google

binary_sensor:
  - platform: mqtt
    name: Motion living room
    state_topic: motion/living_room
    device_class: motion

camera:
  - platform: mjpeg
    mjpeg_url: http://127.0.0.1:8081
    name: Living room

climate:
  - platform: xiaomi_miio
    name: AC partner
    host: !secret lumi_acpartner_v3_host
    token: !secret lumi_acpartner_v3_token
    target_sensor: sensor.ht_bedroom_temperature
    scan_interval: 60

device_tracker:
  - platform: ubus
    host: !secret ubus_host
    username: !secret ubus_username
    password: !secret ubus_password
    dhcp_software: none
    new_device_defaults:
      track_new_devices: False

media_player:
  - platform: braviatv
    host: !secret braviatv_host
    name: Living Room

mqtt:
  discovery: true
  broker: 127.0.0.1
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

recorder:
  db_url: postgres://@/hass

switch:
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac

  - platform: template
    switches:
      media_player_living_room:
        value_template: "{{ states('media_player.living_room') }}"
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.living_room
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.living_room
        icon_template: >-
          {% if is_state('media_player.living_room', 'on') %}
            mdi:television-guide
          {% else %}
            mdi:television
          {% endif %}
      water_heater:
        value_template: "{{ state_attr('climate.ac_partner', 'load_power') | int > 100 }}"
        turn_on:
          service: script.turn_on
          data:
            entity_id: script.water_heater_on
        turn_off:
          service: script.turn_on
          data:
            entity_id: script.water_heater_off
        icon_template: mdi:water

weather:
  - platform: yweather
    name: Hangzhou
    woeid: 2132574

xiaomi_aqara:
  interface: !secret interface
  gateways:
    - mac: !secret lumi_acpartner_v3_mac
      key: !secret lumi_acpartner_v3_key

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml

# logger:
#   logs:
#     homeassistant.components.binary_sensor.xiaomi_aqara: debug
#     homeassistant.components.xiaomi_aqara: debug
#     xiaomi_gateway: debug
#     homeassistant.components.climate.xiaomi_miio: debug
