homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  time_zone: Asia/Shanghai
  unit_system: metric
  customize: !include customize.yaml

automation: !include automations.yaml

config:

conversation:

discovery:

frontend:

group:

history:

http:
  server_host: 127.0.0.1

logbook:

map:

media_player:
  - platform: braviatv
    host: !secret braviatv_host

notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

script: !include scripts.yaml

sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - humidity

sun:

switch:
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac

tts:
  - platform: google

updater:
  reporting: False

zone: !include zones.yaml
