hass_reload:
  alias: Reload Hass
  sequence:
    - alias: Reload Hass groups
      service: group.reload
    - alias: Reload Hass scripts
      service: script.reload
    - alias: Reload Hass automations
      service: automation.reload
    - alias: Reload Hass core
      service: homeassistant.reload_core_config
