title: Home

excluded_entities:
  - automation.disable_zigbee2mqtt_join
  - automation.disable_zigbee2mqtt_join_timer
  - automation.enable_zigbee2mqtt_join
  - automation.flux_living_room_hass_started
  - automation.set_custom_theme_at_startup
  - automation.zigbee2mqtt_log_level
  - binary_sensor.door_bedroom
  - binary_sensor.motion_bedroom
  - binary_sensor.motion_dining_room
  - binary_sensor.motion_living_room
  - camera.living_room
  - climate.ac_partner
  - device_tracker.owntracks_1
  - device_tracker.owntracks_2
  - light.living_room
  - script.hass_reload
  - sensor.season
  - sensor.ht_bedroom_humidity
  - sensor.ht_bedroom_temperature
  - sensor.ht_outside_humidity
  - sensor.ht_outside_temperature
  - sensor.illumination_acpartner
  - sun.sun
  - switch.climate_bedroom
  - switch.reading_living_room
  - switch.tv
  - switch.water_heater

views:
  - title: Home
    id: home
    icon: mdi:view-grid
    cards:
      - type: picture-elements
        image: /local/floorplan.png?v=1
        elements:
          # living room
          - type: state-icon
            entity: binary_sensor.motion_living_room
            style:
              top: 15%
              left: 50%
          - type: state-icon
            entity: binary_sensor.motion_dining_room
            style:
              top: 15%
              left: 68%
          - type: state-icon
            entity: light.living_room
            tap_action: toggle
            style:
              top: 33%
              left: 50%
          - type: state-icon
            entity: switch.tv
            tap_action: toggle
            style:
              top: 55%
              left: 50%
          # living room balcony
          - type: state-icon
            entity: switch.water_heater
            tap_action: toggle
            style:
              top: 17%
              left: 22%
          # bedroom
          - type: state-icon
            entity: binary_sensor.motion_bedroom
            style:
              top: 66%
              left: 18%
          - type: state-icon
            entity: binary_sensor.door_bedroom
            style:
              top: 64.8%
              left: 29.5%
          - type: state-icon
            entity: switch.climate_bedroom
            tap_action: toggle
            style:
              top: 83%
              left: 34%
          - type: state-label
            entity: sensor.ht_bedroom_temperature
            tap_action: navigate
            navigation_path: /lovelace/history
            style:
              top: 90%
              left: 12.5%
          - type: state-label
            entity: sensor.ht_bedroom_humidity
            tap_action: navigate
            navigation_path: /lovelace/history
            style:
              top: 85%
              left: 12%
          # people
          - type: state-icon
            entity: camera.living_room
            style:
              top: 90%
              left: 87%
          - type: image
            entity: device_tracker.owntracks_1
            image: /local/device_1.jpg
            state_filter:
              not_home: grayscale(100%)
            style:
              top: 85%
              left: 95%
              width: 5%
              border-radius: 50%
          - type: image
            entity: device_tracker.owntracks_2
            image: /local/device_2.jpg
            state_filter:
              not_home: grayscale(100%)
            style:
              top: 93%
              left: 95%
              width: 5%
              border-radius: 50%
          # outside
          - type: state-label
            entity: sensor.ht_outside_temperature
            tap_action: navigate
            navigation_path: /lovelace/history
            style:
              top: 72%
              left: 90%
          - type: state-label
            entity: sensor.ht_outside_humidity
            tap_action: navigate
            navigation_path: /lovelace/history
            style:
              top: 67%
              left: 89.6%

      - type: conditional
        conditions:
          - entity: media_player.tv
            state: 'on'
        card:
          type: media-control
          entity: media_player.tv

      - type: conditional
        conditions:
          - entity: light.living_room
            state: 'on'
        card:
          type: entities
          entities:
            - light.living_room
            - switch.reading_living_room
            - switch.flux_living_room

      - type: conditional
        conditions:
          - entity: switch.climate_bedroom
            state: 'on'
        card:
          type: entities
          entities:
            - climate.bedroom

      - type: conditional
        conditions:
          - entity: weather.hangzhou
            state_not: dummy
        card:
          type: weather-forecast
          entity: weather.hangzhou

  - title: History
    id: history
    icon: mdi:chart-line
    cards:
      - type: history-graph
        entities:
          - sensor.bedroom_humidity
          - sensor.ht_bedroom_humidity
          - sensor.ht_bedroom_temperature
          - sensor.ht_outside_humidity
          - sensor.ht_outside_temperature

  - title: Map
    id: map
    icon: mdi:map
    panel: yes
    cards:
      - type: map
        entities:
          - device_tracker.owntracks_1
          - device_tracker.owntracks_2
          - zone.home
          - zone.work

  - title: Settings
    id: settings
    icon: mdi:settings
    cards:
      - type: entities
        entities:
          - type: call-service
            name: Reload Hass
            icon: mdi:home-assistant
            action_name: Reload
            service: script.hass_reload
            service_data: {}
          - type: call-service
            name: Restart Hass
            icon: mdi:home-assistant
            action_name: Restart
            service: homeassistant.restart
            service_data: {}
          - type: call-service
            name: Test notification
            icon: mdi:message-text
            action_name: Test
            service: notify.html5
            service_data:
              message: This is a test message
      - type: entities
        entities:
          - automation.climate_bedroom_auto_cool
          - automation.climate_bedroom_auto_off
          - automation.flux_living_room_light_on
          - automation.notify_home
          - automation.water_heater
          - automation.water_heater_season
      - type: entities
        show_header_toggle: no
        entities:
          - input_boolean.zigbee2mqtt_permit_join
          - timer.zigbee2mqtt_permit_join
          - input_select.zigbee2mqtt_log_level
