title: Home

excluded_entities:
  - switch.media_player_living_room
  - switch.water_heater

views:
  - title: Home
    id: home
    icon: mdi:view-grid
    cards:
      - type: picture-elements
        image: /local/floorplan.png
        elements:
          - type: state-icon
            entity: switch.media_player_living_room
            tap_action: toggle
            style:
              top: 55%
              left: 50%
          - type: state-icon
            entity: switch.water_heater
            tap_action: toggle
            style:
              top: 18%
              left: 22%
      - type: glance
        entities:
          - device_tracker.1
          - device_tracker.2
          - device_tracker.3
  - title: Media
    id: media
    icon: mdi:cast-connected
    cards:
      - type: media-control
        entity: media_player.living_room
  - title: Weather
    id: weather
    icon: mdi:weather-cloudy
    cards:
      - type: weather-forecast
        entity: weather.hangzhou
  - title: Settings
    id: settings
    icon: mdi:settings
    cards:
      - type: entities
        entities:
          - automation.notify_home
          - automation.water_heater
