title: Home

excluded_entities:
  - binary_sensor.motion_living_room
  - binary_sensor.motion_bedroom
  - camera.living_room
  - device_tracker.owntracks_1
  - device_tracker.owntracks_2
  - light.living_room
  - script.hass_reload
  - sensor.ht_bedroom_humidity
  - sensor.ht_bedroom_temperature
  - sun.sun
  - switch.tv
  - switch.water_heater

views:
  - title: Home
    id: home
    icon: mdi:view-grid
    cards:
      - type: picture-elements
        image: /local/floorplan.png?v=1
        elements:
          # living room
          - type: state-icon
            entity: binary_sensor.motion_living_room
            style:
              top: 15%
              left: 50%
          - type: state-icon
            entity: binary_sensor.motion_dining_room
            style:
              top: 15%
              left: 68%
          - type: state-icon
            entity: light.living_room
            tap_action: toggle
            style:
              top: 33%
              left: 48%
          - type: state-icon
            entity: switch.reading_living_room
            tap_action: toggle
            style:
              top: 33%
              left: 54%
          - type: state-icon
            entity: switch.tv
            tap_action: toggle
            style:
              top: 55%
              left: 50%
          # living room balcony
          - type: state-icon
            entity: switch.water_heater
            tap_action: toggle
            style:
              top: 18%
              left: 22%
          # bedroom
          - type: state-icon
            entity: binary_sensor.motion_bedroom
            style:
              top: 66%
              left: 18%
          - type: state-icon
            entity: binary_sensor.door_bedroom
            style:
              top: 64.8%
              left: 29.5%
          - type: state-icon
            entity: switch.climate_bedroom
            tap_action: toggle
            style:
              top: 79%
              left: 34%
          - type: state-label
            entity: sensor.ht_bedroom_temperature
            style:
              top: 90%
              left: 30%
          - type: state-label
            entity: sensor.ht_bedroom_humidity
            style:
              top: 90%
              left: 12%
          # people
          - type: state-icon
            entity: camera.living_room
            style:
              top: 90%
              left: 87%
          - type: image
            entity: device_tracker.owntracks_1
            image: /local/device_1.jpg
            state_filter:
              not_home: grayscale(100%)
            style:
              top: 85%
              left: 95%
              width: 5%
              border-radius: 50%
          - type: image
            entity: device_tracker.owntracks_2
            image: /local/device_2.jpg
            state_filter:
              not_home: grayscale(100%)
            style:
              top: 93%
              left: 95%
              width: 5%
              border-radius: 50%
          # outside
          - type: state-label
            entity: sensor.ht_outside_temperature
            style:
              top: 72%
              left: 90%
          - type: state-label
            entity: sensor.ht_outside_humidity
            style:
              top: 67%
              left: 89.6%

  - title: Media
    id: media
    icon: mdi:cast-connected
    cards:
      - type: media-control
        entity: media_player.tv
      - type: entities
        entities:
          - climate.bedroom

  - title: Weather
    id: weather
    icon: mdi:weather-partlycloudy
    cards:
      - type: weather-forecast
        entity: weather.hangzhou

  - title: Settings
    id: settings
    icon: mdi:settings
    cards:
      - type: entities
        entities:
          - type: call-service
            name: Reload Hass
            icon: mdi:home-assistant
            action_name: Reload
            service: script.hass_reload
            service_data: {}
          - type: call-service
            name: Restart Hass
            icon: mdi:home-assistant
            action_name: Restart
            service: homeassistant.restart
            service_data: {}
          - automation.notify_home
          - automation.water_heater
          - automation.water_heater_season
          - input_boolean.zigbee2mqtt_permit_join
          - timer.zigbee2mqtt_permit_join
          - input_select.zigbee2mqtt_log_level
