title: Home

excluded_entities:
  - switch.media_player_living_room
  - switch.water_heater

views:
  - title: Home
    id: home
    icon: mdi:view-grid
    cards:
      - type: picture-elements
        image: /local/floorplan.png
        elements:
          - type: state-icon
            entity: switch.media_player_living_room
            tap_action: toggle
            style:
              top: 55%
              left: 50%
          - type: state-icon
            entity: switch.water_heater
            tap_action: toggle
            style:
              top: 18%
              left: 22%
          - type: state-label
            entity: sensor.temperature_bedroom
            style:
              top: 90%
              left: 30%
          - type: state-label
            entity: sensor.humidity_bedroom
            style:
              top: 90%
              left: 12%
          - type: state-icon
            entity: binary_sensor.motion_sensor_living_room
            style:
              top: 15%
              left: 52%
      - type: glance
        show_name: no
        entities:
          - device_tracker.1
          - device_tracker.2
  - title: Media
    id: media
    icon: mdi:cast-connected
    cards:
      - type: media-control
        entity: media_player.living_room
  - title: Weather
    id: weather
    icon: mdi:weather-partlycloudy
    cards:
      - type: weather-forecast
        entity: weather.hangzhou
  - title: Settings
    id: settings
    icon: mdi:settings
    cards:
      - type: entities
        entities:
          - type: call-service
            name: Reload Hass
            icon: mdi:home-assistant
            action_name: Reload
            service: script.hass_reload
            service_data: {}
          - type: call-service
            name: Restart Hass
            icon: mdi:home-assistant
            action_name: Restart
            service: homeassistant.restart
            service_data: {}
          - automation.notify_home
          - automation.water_heater
