---
- name: wireless packages
  apt:
    name:
      - iw
      - wireless-tools
      - wpasupplicant
      - wpagui
      - crda

- name: systemd network
  template:
    dest: /etc/systemd/network/{{ wlan }}.network
    src: wlan.network.j2
    owner: root
    group: root
    mode: '0644'

- name: wpasupplicant
  template:
    dest: /etc/wpa_supplicant/wpa_supplicant-{{ wlan }}.conf
    src: wpa_supplicant.conf.j2
    owner: root
    group: root
    mode: '0600'
  # notify: wpa_cli reconfigure

- name: set crda regdomain
  lineinfile:
    dest: /etc/default/crda
    regexp: ^REGDOMAIN=
    line: REGDOMAIN=CN

- name: disable system wpa_supplicant service
  service:
    name: wpa_supplicant
    enabled: no
    state: stopped

- name: enable system wpa_supplicant@wlan
  service:
    name: wpa_supplicant@{{ wlan }}
    enabled: yes
    state: started
