---
- name: wireless packages
  apt: name={{ item }}
  with_items:
    - iw
    - wireless-tools
    - wpasupplicant
    - crda
    - ifmetric

- name: /etc/network/interfaces.d/wireless
  template:
    dest: /etc/network/interfaces.d/wireless
    src: wireless.j2
    owner: root
    group: root
    mode: '0644'

- name: /etc/wpa_supplicant/wpa_supplicant.conf
  template:
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    src: wpa_supplicant.conf.j2
    owner: root
    group: root
    mode: '0600'
  # notify: wpa_cli reconfigure

- name: set crda regdomain
  lineinfile:
    dest: /etc/default/crda
    regexp: ^REGDOMAIN=
    line: REGDOMAIN=CN
