---
- name: install packages
  apt:
    name: "{{ item }}"
  with_items:
    - ffmpeg
    - mosquitto-clients
    - motion
    - uvcdynctrl
    - v4l-utils

- name: install logrotate rule for uvcdynctrl
  copy:
    dest: /etc/logrotate.d/uvcdynctrl
    src: uvcdynctrl.logrotate

- name: install udev rule to disable led
  copy:
    dest: /etc/udev/rules.d/99-motion.rules
    src: 99-motion.rules
  notify: dpkg-reconfigure linux-image

- name: enable motion daemon
  lineinfile:
    dest: /etc/default/motion
    regexp: ^start_motion_daemon=
    line: start_motion_daemon=yes

- name: set motion target dir permission
  file:
    dest: /var/lib/motion/
    state: directory
    owner: motion
    group: motion
    mode: '2750'

- name: add www-data to motion group
  user:
    name: www-data
    groups: motion
    append: yes

- name: add staff to motion group
  user:
    name: "{{ item.name }}"
    groups: motion
    append: yes
  with_items: "{{ staff }}"

- name: copy generate-sprite script
  copy:
    dest: /etc/motion/generate-sprite
    src: generate-sprite
    mode: '0755'

- name: config motion
  copy:
    dest: /etc/motion/motion.conf
    src: motion.conf
  notify: reload motion
