---
- name: modprobe tcp_bbr
  modprobe:
    name: tcp_bbr

- name: add tcp_bbr to /etc/modules
  lineinfile:
    dest: /etc/modules
    line: tcp_bbr

- name: config sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-tcp-bbr.conf
  with_items:
    - name: net.core.default_qdisc
      value: fq
    - name: net.ipv4.tcp_congestion_control
      value: bbr
