---
- name: install dependences
  apt:
    name: "{{ item }}"
  with_items:
    - build-essential
    - libpython3-dev
    # media_player.vlc
    - vlc-bin
    - vlc-plugin-base
    # notify.html5
    - libffi-dev
    - libssl-dev
    # recoder
    - postgresql
    - postgresql-server-dev-all
    - python-psycopg2
    # web_speech
    - chromium-driver
    - dbus-x11
    - pulseaudio
    - xvfb

- name: create psql db for hass
  postgresql_db:
    name: hass
  become: true
  become_user: postgres

- name: create psql user for hass
  postgresql_user:
    name: hass
    db: hass
  become: true
  become_user: postgres

- name: create hass user
  user:
    name: hass
    uid: 20010
    shell: /bin/bash

- name: add hass to bluetooth group
  user:
    name: hass
    groups: bluetooth
    append: yes

- name: add staff to hass group
  user:
    name: "{{ item.name }}"
    groups: hass
    append: yes
  with_items: "{{ staff }}"

- name: install python3-venv
  apt:
    name: python3-venv

- name: pip3 install homeassistant and psycopg2
  pip:
    name: "{{ item }}"
    virtualenv: /home/hass/venv
    virtualenv_command: /usr/bin/python3 -m venv
  with_items:
    - wheel
    - homeassistant
    - psycopg2
  become: yes
  become_user: hass

- name: create hass config dir
  file:
    dest: /home/hass/config
    state: directory
    owner: hass
    group: hass
    mode: '0750'

- name: rsyslog config
  copy:
    dest: /etc/rsyslog.d/hass.conf
    src: hass.rsyslog
  notify:
    - restart rsyslog

- name: logrotate config
  copy:
    dest: /etc/logrotate.d/hass
    src: hass.logrotate

- name: install systemd service
  copy:
    src: hass.service
    dest: /etc/systemd/system/hass.service
  notify:
    - systemctl daemon-reload

- name: config hass secrets
  copy:
    dest: /home/hass/config/{{ item }}.yaml
    content: "{{ hass[item] }}"
    owner: hass
    group: hass
    mode: '0640'
  with_items:
    - secrets
    - zones
  notify:
    - restart hass
  tags:
    - conf

- include: mosquitto.yml
  tags:
    - mosquitto

- include: zigbee2mqtt.yml
  tags:
    - zigbee

- include: snowboy.yml
  tags:
    - snowboy

- include: workaround.yml
  tags:
    - workaround

- name: enable systemd service
  service:
    name: hass
    state: started
    enabled: yes
