---
# for mqtt notify.html5 recorder
- name: install dependences
  apt:
    name: "{{ item }}"
  with_items:
    - build-essential
    - libffi-dev
    - libpython3-dev
    - libssl-dev
    - mosquitto
    - postgresql
    - postgresql-server-dev-all
    - python-psycopg2

- name: create psql db for hass
  postgresql_db:
    name: hass
  become: true
  become_user: postgres

- name: create psql user for hass
  postgresql_user:
    name: hass
    db: hass
  become: true
  become_user: postgres

- name: create hass user
  user:
    name: hass
    uid: 20010
    shell: /bin/bash

- name: add staff to hass group
  user:
    name: "{{ item.name }}"
    groups: hass
    append: yes
  with_items: "{{ staff }}"

- name: install virtualenv
  apt:
    name: virtualenv

- name: pip3 install homeassistant and psycopg2
  pip:
    name: "{{ item }}"
    virtualenv: /home/hass/venv
    virtualenv_python: python3
  with_items:
    - homeassistant
    - psycopg2
  become: yes
  become_user: hass

- name: create hass config dir
  file:
    dest: /home/hass/config
    state: directory
    owner: hass
    group: hass
    mode: '0750'

- name: rsyslog config
  copy:
    dest: /etc/rsyslog.d/hass.conf
    src: hass.rsyslog
  notify:
    - restart rsyslog

- name: logrotate config
  copy:
    dest: /etc/logrotate.d/hass
    src: hass.logrotate

- name: install systemd service
  copy:
    src: hass.service
    dest: /etc/systemd/system/hass.service
  notify:
    - systemctl daemon-reload

- name: config hass
  copy:
    src: "{{ item }}"
    dest: /home/hass/config/{{ item }}
    owner: hass
    group: hass
  with_items:
    - automations.yaml
    - customize.yaml
    - ui-lovelace.yaml
    - scripts.yaml
  tags:
    - conf

- name: config hass secrets
  copy:
    dest: /home/hass/config/{{ item }}.yaml
    content: "{{ hass[item] }}"
    owner: hass
    group: hass
    mode: '0640'
  with_items:
    - secrets
    - zones
  notify:
    - restart hass
  tags:
    - conf

- name: copy www directory
  synchronize:
    src: www/
    dest: /home/hass/config/www/
    rsync_path: sudo -u hass rsync
  tags:
    - conf

- name: config hass
  copy:
    dest: /home/hass/config/configuration.yaml
    src: configuration.yaml
    owner: hass
    group: hass
  notify:
    - restart hass
  tags:
    - conf

- name: enable systemd service
  service:
    name: hass
    state: started
    enabled: yes

- include: acpartner.yml
  tags:
    - acpartner

- include: zigbee2mqtt.yml
  tags:
    - zigbee
