- name: install mosquitto
  apt:
    name: mosquitto

- name: config mosquitto
  copy:
    dest: /etc/mosquitto/mosquitto.acl
    src: mosquitto.acl
  notify:
    - reload mosquitto

- name: config mosquitto
  copy:
    dest: /etc/mosquitto/conf.d/local.conf
    src: mosquitto.conf
  notify:
    - reload mosquitto

- name: config mosquitto users
  copy:
    dest: /etc/mosquitto/mosquitto.users
    content: "{{ mosquitto_users }}"
    owner: mosquitto
    group: mosquitto
    mode: '0640'
  notify:
    - reload mosquitto
