---
- name: install packages
  apt:
    name: "{{ item }}"
  with_items:
    - libatlas-base-dev
    - portaudio19-dev
    - python3-dev
    # - sox
    - swig

- name: pip3 install snowboy
  pip:
    name: git+https://github.com/Kitt-AI/snowboy.git#egg=snowboy
    virtualenv: /home/hass/venv
    virtualenv_command: /usr/bin/python3 -m venv
    editable: no
  become: yes
  become_user: hass

- name: add hass to audio group
  user:
    name: hass
    groups: audio
    append: yes
