- name: workaround for yeelight
  lineinfile:
    dest: /home/hass/venv/lib/python3.6/site-packages/homeassistant/components/light/yeelight.py
    regexp: ^YEELIGHT_RGB_MIN_KELVIN =
    line: YEELIGHT_RGB_MIN_KELVIN = 2700
