---
- name: deb multimedia sources.list
  apt_repository: repo='deb http://www.deb-multimedia.org {{ ansible_lsb.codename }} main non-free'

- name: install deb-multimedia-keyring
  apt:
    name: deb-multimedia-keyring
    force: yes
  register: dmo_keyring

- name: update apt cache
  apt:
    update_cache: yes
  when: dmo_keyring.changed
