- name: adobe flash setting dir
  file:
    dest: /etc/adobe/
    state: directory

- name: adobe flash setting for firefox
  copy: src=mms.cfg dest=/etc/adobe/mms.cfg

# XXX: If this fails, run chromium once
- name: adobe flash setting dir for chromium
  file:
    dest: /home/{{ item.name }}/.config/chromium/Default/Pepper Data/Shockwave Flash/System/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ staff }}"

- name: adobe flash setting for chromium
  copy:
    src: mms.cfg
    dest: /home/{{ item.name }}/.config/chromium/Default/Pepper Data/Shockwave Flash/System/
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ staff }}"

# XXX: If this fails, run firefox with freshplayerplugin once
- name: adobe flash setting dir for freshplayerplugin
  file:
    dest: /home/{{ item.name }}/.config/freshwrapper-data/Shockwave Flash/System/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ staff }}"

- name: adobe flash setting for freshplayerplugin
  copy:
    src: mms.cfg
    dest: /home/{{ item.name }}/.config/freshwrapper-data/Shockwave Flash/System/mms.cfg
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ staff }}"

- name: firefox settings
  template:
    dest: /etc/firefox/ansible-managed.js
    src: firefox-ansible-managed.js.j2
