- name: config keyboard
  lineinfile:
    dest: /etc/default/keyboard
    regexp: ^XKBOPTIONS
    line: XKBOPTIONS="{{ keyboard.xkboptions }}{% if keyboard.xkboptions_extra is defined %},{{ keyboard.xkboptions_extra }}{% endif %}"
  notify: reconfigure keyboard-configuration

- name: config console font
  lineinfile:
    dest: /etc/default/console-setup
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: ^FONTFACE
      line: FONTFACE="TerminusBold"
    - regexp: ^FONTSIZE
      line: FONTSIZE="12x24"
  notify: reconfigure console-setup
