---
- name: test intel graphic card
  shell: lspci -nn | grep -q 'VGA.*8086'
  register: intel_graphic
  ignore_errors: True
  changed_when: False

- name: intel graphic driver
  apt: name={{ item }}
  when: intel_graphic|success
  with_items:
    - xserver-xorg-video-intel
    - libgl1-mesa-dri
    - i965-va-driver

- name: test nvidia graphic card
  shell: lspci -nn | grep -q 'VGA.*10de'
  register: nvidia_graphic
  ignore_errors: True
  changed_when: False

- name: nvidia graphic driver
  apt: name={{ item }}
  when: nvidia_graphic|success
  with_items:
    - linux-headers-amd64
    - nvidia-driver
    - libgles1-nvidia
    - libgles2-nvidia

- name: X11 config dir
  file: dest=/etc/X11/xorg.conf.d/ state=directory
  when: nvidia_graphic|success

- name: nvidia graphic driver
  copy: src=nvidia.conf dest=/etc/X11/xorg.conf.d
  when: nvidia_graphic|success

- name: install cron to auto clean up .xsession-errors
  cron:
    name: auto clean up .xsession-errors
    user: "{{ item.name }}"
    job: test $(stat -c\%s ~/.xsession-errors) -gt 10485760 && > ~/.xsession-errors
    hour: 12
    minute: 7
  with_items: staff

- name: desktop base packages
  apt: name={{ item }}
  with_items:
    - xserver-xorg              ## X
    - xinit
    - x11-xserver-utils         #  xrdb/xmodmap
    - hsetroot                  #  set wallpaper
    - xdotool
    - unclutter                 #  auto hide cursor
    - dmz-cursor-theme
    - redshift                  #  ease your eyes
    - zsh                       ## Shell
    - i3-wm                     ## WM
    - i3status
    - i3lock
    - rofi
    - alsa-utils                ## Utils
    - lxterminal
    - xtermcontrol              #  for set lxterminal color scheme
    - xfce4-clipman
    - vim-gtk                   ## Editor
    - exuberant-ctags           #  vim tagbar plugin
    - emacs
    - xfonts-terminus           #  emacs ime bug
    - aspell                    #  emacs flycheck
    - aspell-en
    - fonts-nanum               #  for spacemacs to display unicode symbol on mode-line
    - chromium                  ## Browser
    - pepperflashplugin-nonfree
    - iceweasel
    - gstreamer1.0-libav        #  for H.264 playback
    - gstreamer1.0-plugins-good
    - gstreamer1.0-vaapi
    - dialog                    ## IME
    - fcitx-config-gtk
    - fcitx-frontend-gtk2
    - fcitx-frontend-gtk3
    - fcitx-frontend-qt4
    - fcitx-googlepinyin
    - fcitx-ui-classic
    - dbus-x11
    - im-config
    - viewnior                  ## Image viewer
    - evince-gtk                ## PDF viewer
    - poppler-data              #  CJK pdf

- name: unclutter settings
  lineinfile:
    dest: /etc/default/unclutter
    regexp: ^EXTRA_OPTS=
    line: EXTRA_OPTS=""

- name: font packages
  apt: name={{ item }}
  with_items: font.pkgs

- name: fontconfig settings, local.conf
  template: src=fontconfig.j2 dest=/etc/fonts/local.conf

- name: fontconfig settings, enable from conf.avail
  file: src=../conf.avail/{{ item }} dest=/etc/fonts/conf.d/{{ item }} state=link force=yes
  with_items: font.enable

- name: theme packages
  apt: name={{ item }}
  with_items: theme.pkgs

- name: numix gtk theme
  git: dest=/usr/share/themes/Numix repo=https://github.com/shimmerproject/Numix.git

- name: gtk2 config
  template: src=gtk2.j2 dest=/etc/gtk-2.0/gtkrc

- name: gtk3 config
  template: src=gtk3.j2 dest=/etc/gtk-3.0/settings.ini

- name: qt4 config
  template: src=qt4.j2 dest=/etc/xdg/Trolltech.conf

# Hack here. When no desktop environment is detected, qt4 use hicolor as
# fallback icon theme. Let hicolor inherit theme.icon and theme.icon will be
# used.
- name: qt4 icon theme
  lineinfile:
    dest: /usr/share/icons/hicolor/index.theme
    insertafter: ^Name=Hicolor$
    regexp: ^Inherits=
    line: Inherits={{ theme.icon }}
  when: theme.icon is defined

- name: qt5 env
  template: src=qt-env.j2 dest=/etc/X11/Xsession.d/20qt-env

- name: adobe flash setting dir
  file:
    dest: /etc/adobe/
    state: directory

- name: adobe flash setting for firefox
  copy: src=mms.cfg dest=/etc/adobe/mms.cfg

# XXX: If this fails, run chromium once
- name: adobe flash setting dir for chromium
  file:
    dest: /home/{{ item.name }}/.config/chromium/Default/Pepper Data/Shockwave Flash/System/
    state: directly
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: staff

- name: adobe flash setting for chromium
  copy:
    src: mms.cfg
    dest: /home/{{ item.name }}/.config/chromium/Default/Pepper Data/Shockwave Flash/System/
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: staff

# XXX: If this fails, run firefox with freshplayerplugin once
- name: adobe flash setting dir for freshplayerplugin
  file:
    dest: /home/{{ item.name }}/.config/freshwrapper-data/Shockwave Flash/System/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: staff

- name: adobe flash setting for freshplayerplugin
  copy:
    src: mms.cfg
    dest: /home/{{ item.name }}/.config/freshwrapper-data/Shockwave Flash/System/mms.cfg
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: staff

- name: zsh config to startx at login
  template: src=zlogin.j2 dest=/home/{{ item.name }}/.zlogin owner={{ item.name }} group={{ item.name }}
  with_items: staff
