---
- name: X11 config dir
  file: dest=/etc/X11/xorg.conf.d/ state=directory

# Install xserver-xorg-input-joystick to control mouse using joystick
- name: xbox 360 pad setting
  copy: src=xbox-360-pad.conf dest=/etc/X11/xorg.conf.d

- name: synaptics config
  copy:
    src: synaptics.conf
    dest: /etc/X11/xorg.conf.d/

- name: test intel graphic card
  shell: lspci -nn | grep -q 'VGA.*8086'
  register: intel_graphic
  ignore_errors: True
  changed_when: False

- name: intel graphic driver
  apt: name={{ item }}
  when: intel_graphic|success
  with_items:
    - xserver-xorg-video-intel
    - libgl1-mesa-dri
    - i965-va-driver
    - vainfo

- name: intel graphic driver config
  copy: src=intel.conf dest=/etc/X11/xorg.conf.d/
  when: intel_graphic|success

- name: test nvidia graphic card
  shell: lspci -nn | grep -q 'VGA.*10de'
  register: nvidia_graphic
  ignore_errors: True
  changed_when: False

- name: nvidia graphic driver
  apt: name={{ item }}
  when: nvidia_graphic|success
  with_items:
    - linux-headers-amd64
    - nvidia-driver
    - libgles1-nvidia
    - libgles2-nvidia

- name: nvidia graphic driver config
  copy: src=nvidia.conf dest=/etc/X11/xorg.conf.d/
  when: nvidia_graphic|success

- name: logrotate config to clean up .xsession-errors
  copy:
    dest: /etc/logrotate.d/ansible-managed
    src: logrotate-ansible-managed

- name: desktop base packages
  apt: name={{ item }}
  with_items:
    - xserver-xorg              ## X
    - xinit
    - x11-xserver-utils         #  xrdb/xmodmap
    - xdg-user-dirs             #  auto create well known user dirs
    - hsetroot                  #  set wallpaper
    - xinput
    - xdotool
    - unclutter                 #  auto hide cursor
    # - dmz-cursor-theme
    - redshift                  #  ease your eyes
    - zsh                       ## Shell
    - zgen
    - zsh-syntax-highlighting
    - i3-wm                     ## WM
    - i3status
    - i3lock
    - xautolock
    - imagemagick
    - rofi
    - alsa-utils                ## Sound
    - lxterminal                ## Terminal
    - xtermcontrol              #  for set lxterminal color scheme
    - xfce4-clipman
    - dunst                     # notification daemon
    - libnotify-bin
    - arandr
    - vim-gtk                   ## Editor
    - exuberant-ctags           #  vim tagbar plugin
    - emacs
    - emacs-goodies-el
    - python-jedi               # for emacs anaconda-mode
    - python-six
    - xfonts-terminus           #  emacs ime bug
    - aspell                    #  emacs flycheck
    - aspell-en
    - chromium                  ## Browser
    - pepperflashplugin-nonfree
    - firefox
    - browser-plugin-freshplayer-pepperflash
    - gstreamer1.0-libav        #  for H.264 playback
    - gstreamer1.0-plugins-good
    - gstreamer1.0-vaapi
    - fcitx                     ## IME
    - fcitx-config-gtk
    - fcitx-frontend-gtk2
    - fcitx-frontend-gtk3
    - fcitx-frontend-qt4
    - fcitx-frontend-qt5
    - fcitx-ui-classic
    - fcitx-rime
    - librime-data-double-pinyin
    - librime-data-pinyin-simp
    - dbus-x11
    - dialog
    - im-config
    - mpv                       ## Video player
    - ffmpeg
    - nomacs                    ## Image viewer
    - scrot
    - evince                    ## PDF viewer
    - poppler-data              #  CJK pdf
    - gpick                     ## Color picker
    - duc                       ## Disk usage
    - freerdp-x11               ## Remote desktop client
    - libfreerdp-plugins-standard
    - pass                      ## Utils
    - pinentry-gtk2
    - git-remote-gcrypt
    - shellcheck
    - sshfs
    - makepasswd
    - whois
    - sqlite3
    - mosh
    - archivemount
    - powertop
    # - apt-listbugs

- name: create dmenu symlink to rofi
  file:
    dest: /usr/local/bin/dmenu
    src: /usr/bin/rofi
    state: link

- name: config keyboard
  lineinfile:
    dest: /etc/default/keyboard
    regexp: ^XKBOPTIONS
    line: XKBOPTIONS="{{ keyboard.xkboptions }}"
  notify: reconfigure keyboard-configuration

- name: config console font
  lineinfile:
    dest: /etc/default/console-setup
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: ^FONTFACE
      line: FONTFACE="TerminusBold"
    - regexp: ^FONTSIZE
      line: FONTSIZE="12x24"
  notify: reconfigure console-setup

- name: alsa config
  template:
    src: asound.conf.j2
    dest: /etc/asound.conf
  when: alsa is defined

- name: list backlight sysfs
  shell: ls -1 /sys/class/backlight/*/brightness /sys/class/backlight/*/bl_power
  changed_when: False
  ignore_errors: True
  register: backlight_sysfs

- name: set backlight sysfs permission once
  file:
    dest: "{{ item }}"
    owner: root
    group: video
    mode: 0664
  with_items: "{{ backlight_sysfs.stdout_lines }}"

- name: copy udev rule to set backlight sysfs permission
  copy:
    src: 99-backlight-permission.rules
    dest: /etc/udev/rules.d/99-backlight-permission.rules

- name: set kbdlight sysfs permission once
  file:
    dest: /sys/class/leds/smc::kbd_backlight/brightness
    owner: root
    group: video
    mode: 0664
  ignore_errors: True

- name: copy udev rule to set kbdlight sysfs permission
  copy:
    src: 99-kbdlight-permission.rules
    dest: /etc/udev/rules.d/99-kbdlight-permission.rules

- name: unclutter settings
  lineinfile:
    dest: /etc/default/unclutter
    regexp: ^EXTRA_OPTS=
    line: EXTRA_OPTS=""

- name: font packages
  apt: name={{ item }}
  with_items: "{{ font.pkgs }}"

- name: fontconfig settings, local.conf
  template: src=fontconfig.j2 dest=/etc/fonts/local.conf

- name: fontconfig settings, enable from conf.avail
  file: src=../conf.avail/{{ item }} dest=/etc/fonts/conf.d/{{ item }} state=link force=yes
  with_items: "{{ font.enable }}"

- name: theme packages
  apt: name={{ item }}
  with_items: "{{ theme.pkgs }}"

- name: download theme deb packages
  get_url:
    dest: "{{ item.dest }}"
    sha256sum: "{{ item.sha256sum }}"
    url: "{{ item.url }}"
  with_items: "{{ theme.debs }}"

- name: install theme deb packages
  apt:
    deb: "{{ item.dest }}"
  with_items: "{{ theme.debs }}"

- name: gtk2 config
  template: src=gtk2.j2 dest=/etc/gtk-2.0/gtkrc

- name: gtk3 config
  template: src=gtk3.j2 dest=/etc/gtk-3.0/settings.ini

- name: qt4 config
  template: src=qt4.j2 dest=/etc/xdg/Trolltech.conf

# Hack here. When no desktop environment is detected, qt4 use hicolor as
# fallback icon theme. Let hicolor inherit theme.icon and theme.icon will be
# used.
# - name: qt4 icon theme
#   lineinfile:
#     dest: /usr/share/icons/hicolor/index.theme
#     insertafter: ^Name=Hicolor$
#     regexp: ^Inherits=
#     line: Inherits={{ theme.icon }}
#   when: theme.icon is defined

- name: custom xsession.d config
  template: src=20ansible-managed.j2 dest=/etc/X11/Xsession.d/20ansible-managed

- name: adobe flash setting dir
  file:
    dest: /etc/adobe/
    state: directory

- name: adobe flash setting for firefox
  copy: src=mms.cfg dest=/etc/adobe/mms.cfg

# XXX: If this fails, run chromium once
- name: adobe flash setting dir for chromium
  file:
    dest: /home/{{ item.name }}/.config/chromium/Default/Pepper Data/Shockwave Flash/System/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ staff }}"

- name: adobe flash setting for chromium
  copy:
    src: mms.cfg
    dest: /home/{{ item.name }}/.config/chromium/Default/Pepper Data/Shockwave Flash/System/
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ staff }}"

# XXX: If this fails, run firefox with freshplayerplugin once
- name: adobe flash setting dir for freshplayerplugin
  file:
    dest: /home/{{ item.name }}/.config/freshwrapper-data/Shockwave Flash/System/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ staff }}"

- name: adobe flash setting for freshplayerplugin
  copy:
    src: mms.cfg
    dest: /home/{{ item.name }}/.config/freshwrapper-data/Shockwave Flash/System/mms.cfg
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ staff }}"

- name: zsh config to startx at login
  template:
    src: zprofile.j2
    dest: ~{{ item.name }}/.zprofile
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ staff }}"

- name: system xresources
  template:
    dest: /etc/X11/Xresources/ansible-managed
    src: xresources-ansible-managed.j2
