---
- name: test intel graphic card
  shell: lspci -nn | grep -q 'VGA.*8086'
  register: intel_graphic
  ignore_errors: True
  changed_when: False
- name: intel graphic driver
  apt: name={{ item }}
  when: intel_graphic|success
  with_items:
    - xserver-xorg-video-intel
    - libgl1-mesa-dri
    - libvdpau-va-gl1

- name: desktop base packages
  apt: name={{ item }}
  with_items:
    - xserver-xorg
    - zsh
    - i3-wm
    - dmz-cursor-theme
    - fonts-wqy-microhei
    - fonts-croscore
    - fonts-crosextra-caladea
    - fonts-crosextra-carlito
    - alsa-utils
    - rxvt-unicode-256color
    - vim-gtk
    - chromium
    - pepperflashplugin-nonfree
    - iceweasel
    - flashplugin-nonfree
    - dialog
    - fcitx-config-gtk
    - fcitx-frontend-gtk2
    - fcitx-frontend-gtk3
    - fcitx-frontend-qt4
    - fcitx-googlepinyin
    - fcitx-ui-classic
    - im-config
