---
- name: test intel graphic card
  shell: lspci -nn | grep -q 'VGA.*8086'
  register: intel_graphic
  ignore_errors: True
- name: intel graphic driver
  apt: name={{ item }}
  when: intel_graphic|success
  with_items:
    - xserver-xorg-video-intel
    - libgl1-mesa-dri
    - libvdpau-va-gl1

- name: desktop base packages
  apt: name={{ item }}
  with_items:
    - xserver-xorg
    - zsh
    - openbox
    - lightdm
    - dmz-cursor-theme
    - fonts-wqy-microhei
    - fonts-croscore
    - fonts-crosextra-caladea
    - fonts-crosextra-carlito
    - alsa-utils
    - rxvt-unicode-256color
    - chromium
    - pepperflashplugin-nonfree
    - iceweasel
    - flashplugin-nonfree
