---
# POST:
# fcitx-config-gtk3 -> Input Method
#                   -> + -> [ ] Only Show Current Language -> Rime
#                   -> - -> Keyboard - English (US)
# firefox -> run init-firefox to install vimfx
#         -> ,B to bootstrap
#         -> ,u to bootstrap ublock

- include: xorg.yml
- include: graphic-driver.yml
- include: package.yml
- include: alsa.yml
- include: console.yml
- include: udev.yml
- include: font.yml
- include: theme.yml
- include: browser.yml
- include: misc.yml
