---
- name: test intel graphic card
  shell: lspci -nn | grep -q 'VGA.*8086'
  register: intel_graphic
  ignore_errors: True
  changed_when: False

- name: intel graphic driver
  apt: name={{ item }}
  when: intel_graphic|success
  with_items:
    - xserver-xorg-video-intel
    - libgl1-mesa-dri
    - libvdpau-va-gl1

- name: desktop base packages
  apt: name={{ item }}
  with_items:
    - xserver-xorg              ## X
    - xinit
    - x11-xserver-utils         #  xrdb/xmodmap
    - xloadimage                #  xsetbg
    - dmz-cursor-theme
    - fonts-wqy-microhei
    - zsh                       ## Shell
    - i3-wm                     ## WM
    - i3status
    - suckless-tools
    - alsa-utils                ## Utils
    - xterm
    - vim-gtk
    - chromium                  ## Browser
    - pepperflashplugin-nonfree
    - iceweasel
    - flashplugin-nonfree
    - dialog                    ## IME
    - fcitx-config-gtk
    - fcitx-frontend-gtk2
    - fcitx-frontend-gtk3
    - fcitx-frontend-qt4
    - fcitx-googlepinyin
    - fcitx-ui-classic
    - dbus-x11
    - im-config
    - viewnior                  ## Image viewer

- name: font packages
  apt: name={{ item }}
  with_items: font.pkgs

- name: fontconfig settings, local.conf
  template: src=fontconfig.j2 dest=/etc/fonts/local.conf

- name: fontconfig settings, enable from conf.avail
  file: src=../conf.avail/{{ item }} dest=/etc/fonts/conf.d/{{ item }} state=link force=yes
  with_items: font.enable

- name: theme packages
  apt: name={{ item }}
  with_items: theme.pkgs

- name: numix gtk theme
  git: dest=/usr/share/themes/Numix repo=https://github.com/shimmerproject/Numix.git

- name: gtk2 config
  template: src=gtk2.j2 dest=/etc/gtk-2.0/gtkrc

- name: gtk3 config
  template: src=gtk3.j2 dest=/etc/gtk-3.0/settings.ini

- name: qt4 config
  template: src=qt4.j2 dest=/etc/xdg/Trolltech.conf

- name: qt5 config
  template: src=qt5.j2 dest=/etc/X11/Xsession.d/20qt5-style
  when: theme.qt5 is defined

- name: qt5 config absent
  file: dest=/etc/X11/Xsession.d/20qt5-style state=absent
  when: theme.qt5 is not defined

- name: zsh config to startx at login
  template: src=zlogin.j2 dest=/home/{{ item.name }}/.zlogin owner={{ item.name }} group={{ item.name }}
  with_items: staff
