- name: list backlight sysfs
  shell: ls -1 /sys/class/backlight/*/brightness
  changed_when: False
  ignore_errors: True
  register: backlight_sysfs

- name: set backlight sysfs permission once
  file:
    dest: "{{ item }}"
    group: video
    mode: g+w
  with_items: "{{ backlight_sysfs.stdout_lines }}"

- name: list leds sysfs
  shell: ls -1 /sys/class/leds/*/brightness
  changed_when: False
  ignore_errors: True
  register: leds_sysfs

- name: set leds sysfs permission once
  file:
    dest: "{{ item }}"
    group: input
    mode: g+w
  with_items: "{{ leds_sysfs.stdout_lines }}"
