- name: X11 config dir
  file: dest=/etc/X11/xorg.conf.d/ state=directory

# Install xserver-xorg-input-joystick to control mouse using joystick
- name: xbox 360 pad setting
  copy: src=xbox-360-pad.conf dest=/etc/X11/xorg.conf.d

- name: synaptics config
  copy:
    src: synaptics.conf
    dest: /etc/X11/xorg.conf.d/

- name: X11 keyboard config
  template:
    src: keyboard.conf.j2
    dest: /etc/X11/xorg.conf.d/keyboard.conf

- name: extra xkb symbols
  copy:
    src: xkb_symbols_search
    dest: /usr/share/X11/xkb/symbols/search

- name: extra xkb rules evdev
  lineinfile:
    dest: /usr/share/X11/xkb/rules/evdev
    insertafter: ^!\s*option\s*=\s*symbols
    line: '  search:win = +search(win)'

- name: extra xkb rules evdev.lst
  lineinfile:
    dest: /usr/share/X11/xkb/rules/evdev.lst
    insertafter: ^!\s*option$
    line: '  search:win           XF86Search as Mod4'

- name: logrotate config to clean up .xsession-errors
  copy:
    dest: /etc/logrotate.d/ansible-managed
    src: logrotate-ansible-managed
