---
- name: install resolvconf
  apt:
    name: resolvconf

- name: install dnsmasq
  apt: name=dnsmasq

- name: config dnsmasq
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.d/chinadns.conf
  notify: restart dnsmasq

- name: install chinadns blob
  get_url:
    dest: /usr/local/bin/chinadns
    url: https://github.com/azuwis/blob/raw/master/chinadns
    sha256sum: 22dc66f1e3854140f118db896c9404532435068306978429bc83678b07eac407
    mode: '0755'

- name: install systemd service for chinadns
  copy:
    src: chinadns.service
    dest: /etc/systemd/system/
  notify: systemctl daemon-reload

- name: copy environ file for chinadns
  copy:
    src: chinadns.default
    dest: /etc/default/chinadns
  notify: restart chinadns

- name: copy resolv config for chinadns
  copy:
    src: chinadns-resolvconf
    dest: /etc/resolvconf/update.d/chinadns
    mode: '0755'

- name: get iplist for chinadns
  get_url:
    dest: /etc/chinadns.list
    url: https://github.com/clowwindy/ChinaDNS/raw/master/iplist.txt
  notify: restart chinadns

- name: enable systemd service for chinadns
  service:
    name: chinadns
    enabled: yes

- name: ensure services are started
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - chinadns
    - dnsmasq

- include: pdnsd.yml
