---
- name: install resolvconf
  apt:
    name: resolvconf

- name: install dnsmasq
  apt: name=dnsmasq

- name: config dnsmasq
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.d/chinadns.conf
  notify: restart dnsmasq

- name: install systemd service for chinadns
  copy:
    src: chinadns.service
    dest: /etc/systemd/system/

- name: copy environ file for chinadns
  copy:
    src: chinadns.default
    dest: /etc/default/chinadns
  notify: restart chinadns

- name: get iplist for chinadns
  get_url:
    dest: /etc/chinadns.list
    url: https://github.com/clowwindy/ChinaDNS/raw/master/iplist.txt
  notify: restart chinadns

- name: enable systemd service for chinadns
  service:
    name: chinadns
    enabled: yes

- name: install unbound
  apt: name=unbound

# XXX: Should stop the service before modify these configs?
- name: config /etc/default/unbound
  copy:
    src: unbound.default
    dest: /etc/default/unbound
  notify: restart unbound

- name: disable unbound resolvconf upstream forward
  file:
    dest: /etc/resolvconf/update.d/unbound
    mode: a-x
  notify: restart unbound

- name: config unbound
  copy:
    src: unbound.conf
    dest: /etc/unbound/unbound.conf.d/chinadns.conf
  notify: restart unbound

- name: ensure services are started
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - unbound
    - chinadns
    - dnsmasq
