- name: install unbound
  apt:
    name: unbound

# XXX: Should stop the service before modify these configs?
- name: config /etc/default/unbound
  copy:
    src: unbound.default
    dest: /etc/default/unbound
  notify: restart unbound

- name: disable unbound resolvconf upstream forward
  file:
    dest: /etc/resolvconf/update.d/unbound
    mode: a-x
  notify: restart unbound

- name: config unbound
  copy:
    src: unbound.conf
    dest: /etc/unbound/unbound.conf.d/chinadns.conf
  notify: restart unbound

- name: ensure unbound are started
  service:
    name: unbound
    state: started
