---
- name: set hostname
  hostname: name={{ inventory_hostname }}

- name: set domain to {{ domain }}
  lineinfile:
    dest: /etc/hosts
    insertafter: ^127\.0\.0\.1\slocalhost
    line: "127.0.0.1\t{{ inventory_hostname }}.{{ domain }} {{ inventory_hostname }}"

- name: base packages
  apt: name={{ item }}
  with_items:
    - locales
    - less
    - file
    - bash-completion
    - ca-certificates
    - pciutils
    - usbutils
    - ethtool
    - sudo
    - systemd-sysv
    - dbus

- name: locales to generate
  locale_gen: name={{ item }} state=present
  with_items: locales

- name: default locale
  copy: dest=/etc/default/locale content="{{ locales[0] }}\n"

- name: initramfs-tools config
  copy: src=initramfs-misc.conf dest=/etc/initramfs-tools/conf.d/misc.conf
  notify: update initramfs
