---
- name: set hostname
  hostname: name={{ inventory_hostname }}

- name: set domain to {{ domain }}
  lineinfile:
    dest: /etc/hosts
    insertafter: ^127\.0\.0\.1\slocalhost
    line: "127.0.0.1\t{{ inventory_hostname }}.{{ domain }} {{ inventory_hostname }}"

- name: base packages
  apt: name={{ item }}
  with_items:
    - locales
    - less
    - file
    - bash-completion
    - ca-certificates
    - pciutils
    - usbutils
    - dnsutils
    - sysfsutils
    - ethtool
    - sudo
    - systemd-sysv
    - libpam-systemd
    - systemd-cron
    - dbus
    - make
    - telnet
    - tcpdump
    - netcat-openbsd
    - traceroute
    - mtr-tiny
    - sipcalc
    - curl
    - rsync
    - bzip2
    - xz-utils
    - zip
    - unzip
    - unrar
    - p7zip-full
    - p7zip-rar
    - lsof
    - strace
    - tmux
    - ncurses-base
    - ncurses-term
    - debfoster
    - silversearcher-ag
    - tofrodos
    - ncdu
    - os-prober
    - git-hub
    - perl-doc
    - myrepos
    - apt-utils
    - apt-listchanges
    - debsums
    - logrotate
    - manpages
    - manpages-dev
    - man-db
    - console-setup
    - patch
    - moreutils
    - python-pip
    - python-wheel
    - python-setuptools
    - autossh
    - resolvconf
    - dosfstools
    - icdiff
    - psmisc
    - fzy
    - libcap2-bin
    - jq
    - nethogs
    - fasd
    - lr
    - intel-microcode
    - rename

- name: extra packages
  apt:
    name: "{{ item }}"
  with_items: "{{ extra_packages }}"
  when: extra_packages is defined

- name: unneeded packages
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - nscd
    - ntpdate
    - cron
    - installation-report

- name: locales to generate
  locale_gen: name="{{ item }}" state=present
  with_items: "{{ locales }}"

- name: default locale
  copy: dest=/etc/default/locale content="LANG={{ locales[0] }}\n"

- name: set /etc/timezone to {{ timezone }}
  copy: content="{{ timezone }}\n" dest=/etc/timezone
  notify: update timezone

- name: link /etc/localtime
  file:
    dest: /etc/localtime
    src: /usr/share/zoneinfo/{{ timezone }}
    state: link

# - name: initramfs-tools config
#   copy: src=initramfs-misc.conf dest=/etc/initramfs-tools/conf.d/misc.conf
#   notify: update initramfs

- name: addition modules in initramfs
  lineinfile:
    dest: /etc/modules
    line: "{{ item }}"
  with_items: "{{ kernel_modules }}"
  when: kernel_modules is defined
  notify: dpkg-reconfigure linux-image

- name: kernel module blacklist
  template:
    dest: /etc/modprobe.d/blacklist.conf
    src: blacklist.conf.j2
  when: kernel_modules_blacklist is defined
  notify: dpkg-reconfigure linux-image

- name: grub timeout
  lineinfile: dest=/etc/default/grub regexp=^GRUB_TIMEOUT= line=GRUB_TIMEOUT={{ grub.timeout }}
  notify: update grub

- name: grub linux init cmd
  lineinfile:
    dest: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX=
    line: GRUB_CMDLINE_LINUX="{{ grub.cmd }}{% if grub.cmd_extra is defined %} {{ grub.cmd_extra }}{% endif %}"
  notify: update grub

# - name: grub hold shift to display menu
#   copy:
#     dest: /etc/grub.d/31_hold_shift
#     src: 31_hold_shift
#     mode: '0755'
#   notify: update grub

- name: set quiet_boot for grub 10_linux
  lineinfile:
    dest: /etc/grub.d/10_linux
    regexp: ^quiet_boot=
    line: quiet_boot="1"
  notify: update grub

- name: config sshd
  copy:
    dest: /etc/ssh/sshd_config
    src: sshd_config
    owner: root
    group: root
    mode: '0644'

- name: disable ssh.service
  service:
    name: ssh.service
    enabled: no
    state: stopped

- name: enable ssh.socket
  service:
    name: ssh.socket
    enabled: yes
    state: started

- name: config swappiness
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-ansible-managed.conf
  with_items:
    - name: net.ipv4.tcp_fastopen
      value: 3
    - name: vm.swappiness
      value: 10

- name: system network interfaces
  copy:
    dest: /etc/network/interfaces
    src: interfaces

- name: common network interfaces
  template:
    dest: /etc/network/interfaces.d/common
    src: interfaces-common.j2

- name: install blobs
  get_url:
    dest: "{{ item.dest }}"
    url: https://github.com/azuwis/blob/raw/master/{{ item.name }}
    sha256sum: "{{ item.sha256sum }}"
    mode: "{{ item.mode | default('0644') }}"
  when: blobs is defined
  with_items: "{{ blobs | default([]) }}"

# replace syslog with systemd-journald, see http://freedesktop.org/wiki/Software/systemd/Optimizations/
# - name: create /var/log/journal/
#   file:
#     dest: /var/log/journal/
#     state: directory
#     owner: root
#     group: systemd-journal
#     mode: "2755" # need to be quoted, ansible bug?
#   notify: restart journald

# - name: remove rsyslog
#   apt: name=rsyslog state=absent purge=yes
