---
- name: set hostname
  hostname: name={{ inventory_hostname }}

- name: set domain to {{ domain }}
  lineinfile:
    dest: /etc/hosts
    insertafter: ^127\.0\.0\.1\slocalhost
    line: "127.0.0.1\t{{ inventory_hostname }}.{{ domain }} {{ inventory_hostname }}"

- name: base packages
  apt: name={{ item }}
  with_items:
    - locales
    - less
    - file
    - bash-completion
    - ca-certificates
    - pciutils
    - usbutils
    - dnsutils
    - ethtool
    - ntpdate
    - sudo
    - systemd-sysv
    - libpam-systemd
    - curl
    - dbus
    - unzip
    - unrar
    - p7zip-full
    - p7zip-rar
    - rsync
    - tmux
    - debfoster
    - silversearcher-ag
    - tofrodos
    - ncdu
    - os-prober
    - git-hub
    - myrepos

- name: unneeded packages
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - nscd

- name: locales to generate
  locale_gen: name="{{ item }}" state=present
  with_items: locales

- name: default locale
  copy: dest=/etc/default/locale content="LANG={{ locales[0] }}\n"

- name: set /etc/timezone to {{ timezone }}
  copy: content="{{ timezone }}\n" dest=/etc/timezone
  notify: update timezone

# - name: initramfs-tools config
#   copy: src=initramfs-misc.conf dest=/etc/initramfs-tools/conf.d/misc.conf
#   notify: update initramfs

- name: addition modules in initramfs
  lineinfile:
    dest: /etc/initramfs-tools/modules
    line: "{{ item }}"
  with_items: kernel_modules
  when: kernel_modules is defined
  notify: update initramfs

- name: grub timeout
  lineinfile: dest=/etc/default/grub regexp=^GRUB_TIMEOUT= line=GRUB_TIMEOUT={{ grub.timeout }}
  notify: update grub

- name: grub linux init cmd
  lineinfile: dest=/etc/default/grub regexp=^GRUB_CMDLINE_LINUX= line='GRUB_CMDLINE_LINUX="{{ grub.cmd }}"'
  notify: update grub
  when: grub is defined and grub.cmd is defined

- name: config sshd
  copy:
    dest: /etc/ssh/sshd_config
    src: sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: reload ssh

# replace syslog with systemd-journald, see http://freedesktop.org/wiki/Software/systemd/Optimizations/
# - name: create /var/log/journal/
#   file:
#     dest: /var/log/journal/
#     state: directory
#     owner: root
#     group: systemd-journal
#     mode: "2755" # need to be quoted, ansible bug?
#   notify: restart journald

# - name: remove rsyslog
#   apt: name=rsyslog state=absent purge=yes
