---
- name: set hostname
  hostname: name={{ inventory_hostname }}

- name: set domain to {{ domain }}
  lineinfile:
    dest: /etc/hosts
    insertafter: ^127\.0\.0\.1\slocalhost
    line: "127.0.0.1\t{{ inventory_hostname }}.{{ domain }} {{ inventory_hostname }}"

# XXX Not work if locales is already installed
# TODO Use default filter
- name: default locale
  debconf: name=locales question='locales/default_environment_locale' value=en_US.UTF-8 vtype='select'

- name: locales to generate
  debconf: name=locales question='locales/locales_to_be_generated'  value='en_US.UTF-8 UTF-8' vtype='multiselect'

- name: base packages
  apt: name={{ item }}
  with_items:
    - locales
    - less
    - bash-completion
    - ca-certificates
    - pciutils
    - usbutils
    - ethtool
    - sudo

- name: initramfs-tools config
  copy: src=initramfs-misc.conf dest=/etc/initramfs-tools/conf.d/misc.conf
  notify: update initramfs
