---
- name: systemctl daemon-reload
  command: systemctl daemon-reload

- name: restart torrent-ratio
  service:
    name: torrent-ratio
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
