automation:
  - id: enable_zigbee_join
    alias: Enable Zigbee joining
    hide_entity: yes
    trigger:
      platform: state
      entity_id: input_boolean.zigbee_permit_join
      to: 'on'
    action:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/bridge/config/permit_join
          payload: 'true'
      - service: timer.start
        data:
          entity_id: timer.zigbee_permit_join

  - id: disable_zigbee_join
    alias: Disable Zigbee joining
    hide_entity: yes
    trigger:
      platform: state
      entity_id: input_boolean.zigbee_permit_join
      to: 'off'
    action:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/bridge/config/permit_join
          payload: 'false'
      - service: timer.cancel
        data:
          entity_id: timer.zigbee_permit_join

  - id: disable_zigbee_join_timer
    alias: Disable Zigbee joining by timer
    hide_entity: yes
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.zigbee_permit_join
    action:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/bridge/config/permit_join
          payload: 'false'
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.zigbee_permit_join

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: no
    icon: mdi:cellphone-wireless

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600
