---
- name: install torrent-ratio
  get_url:
    dest: /usr/local/bin/torrent-ratio
    url: https://github.com/azuwis/torrent-ratio/releases/download/v0.2/torrent-ratio
    sha256sum: ce50c9939950d834634d134fb127986dffdff5a326645ebf0268bd3820ab49f6
    mode: '0755'

# - name: config torrent-ratio
#   copy:
#     dest: /home/torrent/.torrent-ratio.json
#     src: torrent-ratio.json
#     owner: torrent
#     group: torrent
#   notify: restart torrent-ratio

- name: rsyslog config
  copy:
    dest: /etc/rsyslog.d/torrent-ratio.conf
    src: torrent-ratio.rsyslog
  notify:
    - restart rsyslog

- name: logrotate config
  copy:
    dest: /etc/logrotate.d/torrent-ratio
    src: torrent-ratio.logrotate

- name: install systemd service
  copy:
    src: torrent-ratio.service
    dest: /etc/systemd/system/torrent-ratio.service
  notify: systemctl daemon-reload

- name: enable systemd service
  service:
    name: torrent-ratio
    state: started
    enabled: yes
