# qjackctl:
#   Options -> Execute script after Startup:
#     pactl load-module module-jack-sink channels=2; pactl load-module module-jack-source; pactl set-default-sink jack_out; a2jmidid -e &
#   Misc -> Start JACK audio server on application startup [x]
#        -> Enable ALSA Sequencer support [ ]
- name: install packages
  apt:
    name:
      # ardour
      - a2jmidid
      - ardour
      - pulseaudio-module-jack
      - qjackctl
      # plugins
      - dragonfly-reverb
      - mda-lv2
      - x42-plugins
      # linuxsampler
      - gigedit
      - linuxsampler
      - qsampler
