---
- name: reconfigure keyboard-configuration
  shell: dpkg-reconfigure --frontend noninteractive keyboard-configuration && udevadm trigger --subsystem-match=input --action=change

- name: reconfigure console-setup
  shell: dpkg-reconfigure --frontend noninteractive console-setup

- name: update hwdb
  shell: systemd-hwdb update; udevadm trigger
